import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import {client} from '../lib/client'

const Home =({properties}) =>{
  
  return (
    <div>
      <Head>
        <title>Galla Shakur || Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />



    </div>
  )
}

export const getServerSideProps = async()=>{
  const query = '*[_type == "property"]'
  const properties = await client.fetch(query)

  if(!properties.length){
    return{
      props:{
        properties: [],
      },
    }
  }else{
    return{
      props:{properties}
    }
  }
  
}


export default Home